# Generated by Django 4.2.8 on 2024-05-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('cur_unit', models.CharField(max_length=10)),
                ('cur_nm', models.CharField(max_length=100)),
                ('ttb', models.CharField(max_length=20)),
                ('tts', models.CharField(max_length=20)),
                ('deal_bas_r', models.CharField(max_length=20)),
                ('bkpr', models.CharField(max_length=20)),
                ('yy_efee_r', models.CharField(blank=True, max_length=20, null=True)),
                ('ten_dd_efee_r', models.CharField(blank=True, max_length=20, null=True)),
                ('kftc_deal_bas_r', models.CharField(blank=True, max_length=20, null=True)),
                ('kftc_bkpr', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
