# Generated by Django 4.2.8 on 2024-05-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='없음', unique=True)),
                ('kor_co_nm', models.TextField(default='없음')),
                ('fin_prdt_nm', models.TextField(default='없음')),
                ('etc_note', models.TextField(default='없음')),
                ('join_deny', models.IntegerField(default=-1)),
                ('join_member', models.TextField(default='없음')),
                ('join_way', models.TextField(default='없음')),
                ('spcl_cnd', models.TextField(default='없음')),
            ],
        ),
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='없음', unique=True)),
                ('kor_co_nm', models.TextField(default='없음')),
                ('fin_prdt_nm', models.TextField(default='없음')),
                ('etc_note', models.TextField(default='없음')),
                ('join_deny', models.IntegerField(default=-1)),
                ('join_member', models.TextField(default='없음')),
                ('join_way', models.TextField(default='없음')),
                ('spcl_cnd', models.TextField(default='없음')),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='없음')),
                ('intr_rate_type_nm', models.CharField(default='없음', max_length=100)),
                ('intr_rate', models.FloatField(default=-1)),
                ('intr_rate2', models.FloatField(default=-1)),
                ('save_trm', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.savingproducts')),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(default='없음')),
                ('intr_rate_type_nm', models.CharField(default='없음', max_length=100)),
                ('intr_rate', models.FloatField(default=-1)),
                ('intr_rate2', models.FloatField(default=-1)),
                ('save_trm', models.IntegerField(default=-1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.depositproducts')),
            ],
        ),
    ]
